[build]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.5"
  NODE_VERSION = "16"

  [[headers]]
  for = "/pipeline-report"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Basic-Auth = "pipeline:gotpipes? algorand:gotalgos?"
